# -*- coding: utf-8 -*-
"""soil_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19e8BLgmcC502_rY0kNPUM1SwT3lvmzDb
"""

import numpy as np
import pandas as pd
import keras
from keras.utils import to_categorical

from sklearn.utils import shuffle

from google.colab import files
uploaded = files.upload()

a=pd.read_csv('crop_predict.csv')
a = shuffle(a)
a

X = a.drop(columns = ['Crop_Name'])
X

Y = a['Crop_Name']
unique_names = np.unique(a['Crop_Name'])
unique_names
Y=Y.to_frame()
Y

mapping = { 'Barley' : 0 , 'Corn-Field for silage':1, 'Corn-Field for stover':2,'Millet':3,'Potato':4,'Sugarcane':5 }

Y.Crop_Name = Y.Crop_Name.map(mapping)
Y

y = to_categorical(Y)
y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
print y_train.shape
print y_test.shape

from keras.layers import Dense, Activation
from keras.models import Sequential

model_soil = Sequential()
model_soil.add(Dense(128,input_shape=(4,)))
model_soil.add(Activation('relu'))
model_soil.add(Dense(64))
model_soil.add(Activation('relu'))
model_soil.add(keras.layers.Dropout(0.3))
model_soil.add(Dense(6))
model_soil.add(Activation('softmax'))
model_soil.summary()

model_soil.compile(optimizer='adagrad', loss='categorical_crossentropy', metrics=['accuracy'])

hist = model_soil.fit(X_train, y_train, nb_epoch=50,batch_size=100,verbose=2, shuffle=True ,validation_data=(X_test, y_test))

test_vector2 = [35.33,0.0966,0.01927,1.9344] #value for sugarcane
test_vector = [14.5,2.3,0.5,1.66] # value for barley
test_vector = np.asanyarray(test_vector)

type(test_vector)

test_vector = np.reshape(test_vector,(1,4))

reverse_mapping = ['Barley','Corn-Field for silage','Corn-Field for stover','Millet','Potato','Sugarcane']
reverse_mapping = np.asarray(reverse_mapping)

a = model_soil.predict_classes(test_vector)
#hell yeah this corresponds to barley
prediction = reverse_mapping[a]
print prediction
print 'GREAT SUCCESS!'

print 'Lit as fuck'
print 'pedos rock'

